-- AlterTable
ALTER TABLE "authorizedPersons" ALTER COLUMN "name" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "connections" ALTER COLUMN "password" SET DATA TYPE VARCHAR,
ALTER COLUMN "note" SET DATA TYPE VARCHAR,
ALTER COLUMN "ip" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "currents" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "address" SET DATA TYPE VARCHAR,
ALTER COLUMN "taxOffice" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "password" SET DATA TYPE VARCHAR;
